// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szstvbwapuayaqysnhux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6c3R2YndhcHVheWFxeXNuaHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjkyODAsImV4cCI6MjA3Mjg0NTI4MH0.jXf248-ZRfb4HEwEwPJXQGcT8rk30TOyxSDUFktGHFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});